
name: build

on:
  - push
  - pull_request

jobs:

  test:

    name: Test (Ruby ${{ matrix.ruby }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - '2.1'
          - '2.2'
          - '2.3'
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'

    steps:

      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Test
        run: bundle exec rake --trace
